version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.multistage
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - TZ=UTC
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tezos_delegations
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./sqitch_pg:/app/sqitch_pg
      - ./scripts:/app/scripts

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/api/openapi.yaml
      - BASE_URL=/swagger
    volumes:
      - ./cmd/tezos-delegation-service/specs:/api
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tezos_delegations
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./sqitch_pg:/app/sqitch_pg
    restart: unless-stopped

volumes:
  postgres_data: