apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tezos-delegation-data-pvc
  namespace: tezos-delegation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard