apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tezos-delegation-api-monitor
  namespace: tezos-delegation
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: tezos-delegation-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s