logging:
  level: info
  format: json
  enable_file: false
  file_path: /var/log/tezos-delegation-service.log
  graylog:
    enabled: false
    url: graylog.example.com
    port: 12201
    facility: tezos-delegation-service

database:
  impl: psql
  psql:
    host: db
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: delegations
    sslmode: disable

tzktapi:
  impl: api
  api:
    url: https://api.tzkt.io
  polling_interval: 60

pagination:
  limit: 50

server:
  port: 9090